### ISSUE TITLE
Cannot install via aqua in Windows environment.

### ISSUE THREAD

**Issue by laughk** [Songmu/ecschedule#101]
In Windows environment, [the installation via aqua described in the README](https://github.com/Songmu/ecschedule/blob/ecbe01c40f1b221f5e3da65ca6c3244ed1c02c77/README.md#aqua), it is not actually installed, and the error message "command not fonund" is displayed.

## Example.

> [!NOTE]
> Environment is as follows.
> - Windows11 Pro 22631.3447
> - aqua 2.27.2 (8ef7841a5cbd6afb12f0de71c650f8e4d97fe44b) (installed via scoop)
> - Occurs in cmd, PowerShell, or [nushell](https://www.nushell.sh/)

Here is an example with aqua.yaml with the following contents (For comparison, [kayac/ecspresso](https://github.com/kayac/ecspresso), which distributes Windows binaries, is also included.)

```yaml
❯ bat -p --color=never aqua.yaml
---
# aqua - Declarative CLI Version Manager.
# https://aquaproj.github.io/
# checksum: true
# enabled: true
# require_checksum: true
# supported_envs: true
# - all
registries: # checksum: # enabled: true
- type: standard
  ref: v4.164.0 # renovate: depName=aquaproj/aqua-registry
packages: # - all registries: type: standard ref: v4.164.0
- name: Songmu/ecschedule@v0.11.4
- name: kayac/ecspresso@v2.3.3

❯
````

Run the installation. ecspresso will run the installation process, but there is no log for ecschedule.

```console
❯ aqua i
INFO[0000] create a proxy file                           aqua_version=2.27.2 env=windows/amd64 program=aqua proxy_path="C:\\Users\\laughk\\AppData\\Local\\aquaproj-aqua\\bin\\ecspresso"
INFO[0000] create a proxy file                           aqua_version=2.27.2 env=windows/amd64 program=aqua proxy_path="C:\\Users\\laughk\\AppData\\Local\\aquaproj-aqua\\bat\\ecspresso.bat"
INFO[0000] download and unarchive the package            aqua_version=2.27.2 env=windows/amd64 package_name=kayac/ecspresso package_version=v2.3.3 program=aqua registry=standard
WARN[0002] remove a temporal file                        aqua_version=2.27.2 env=windows/amd64 error="remove C:\\Users\\laughk\\AppData\\Local\\Temp\\040508135: The process cannot access the file because it is being used by another process." package_name=kayac/ecspresso package_version=v2.3.3 program=aqua registry=standard

❯ 
```

Check command. ecschedule will be `command not found`.

```console
❯ aqua exec -- ecspresso version
ecspresso v2.3.3

❯ aqua exec -- ecschedule -version
FATA[0000] aqua failed aqua_version=2.27.2 doc="https://aquaproj.github.io/docs/reference/codes/004" env=windows/amd64 error="command is not found" exe_name=ecschedule program=aqua
```

# Possible solutions

I am not sure, but I think that this problem might be solved if you distribute the binaries for Windows via GitHub Release.

**Comment by Songmu** [comment]
I built an executable for the Win on releasing v0.12.0. Please try it after Aqua's index is updated.

**Comment by laughk** [comment]
@Songmu 

Thank you for providing support for the Windows executable distribution! I am very pleased. However, it appears that support is also needed in  [aqua-registry](https://github.com/aquaproj/aqua-registry), and at this point, the installation via aqua in the Windows environment is still not possible.

```console
❯ bat -p aqua.yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.202.0  # renovate: depName=aquaproj/aqua-registry
packages:
- name: Songmu/ecschedule@v0.12.0

❯ aqua i

❯ aqua exec -- ecschedule -version
FATA[0000] aqua failed                                   aqua_version=2.29.0 doc="https://aquaproj.github.io/docs/reference/codes/004" env=windows/amd64 error="command is not found" exe_name=ecschedule program=aqua

```

I have submitted the following pull request for the aqua-registry changes. If it is incorporated in some way, ecschedule via aqua will be available under Windows this time.

https://github.com/aquaproj/aqua-registry/pull/24709

**Comment by laughk** [comment]
@Songmu 

[aqua-registry v4.202.1 has been released](https://github.com/aquaproj/aqua-registry/releases/tag/v4.202.1) and I have confirmed that ecschedule can be installed using aqua on windows!

```console
❯ wmic os get Caption,Version,BuildNumber
BuildNumber  Caption                   Version
22631        Microsoft Windows 11 Pro  10.0.22631

❯ bat -p aqua.yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.202.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: Songmu/ecschedule@v0.12.0

❯ aqua i

❯ aqua exec -- ecschedule -version
ecschedule v0.12.0 (rev:586cc61)
```
